<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
     <LangVersion>10</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Unity3D.UnityEngine" Version="2018.3.5.1" />
    <PackageReference Include="UnityEngine.CoreModule" Version="2020.3.1" />
    <Reference Include="Assembly-CSharp-firstpass" HintPath="libs\Assembly-CSharp-firstpass.dll" />
  </ItemGroup>

</Project>
